name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_NAME=docker.io/library/openstock
        IMAGE_TAG=${{ github.run_number }}
        docker build . \
          --file Dockerfile \
          --tag "${IMAGE_NAME}:${IMAGE_TAG}" \
          --tag "${IMAGE_NAME}:latest"
